# Generated by Django 5.2.4 on 2025-08-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_event_start_date_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentplan',
            name='finish_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='start_date',
            field=models.DateField(),
        ),
    ]
