# Generated by Django 5.2.4 on 2025-07-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_analysispackage_medicalspecialty_vaccination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='analysis_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.analysistest'),
        ),
        migrations.AddField(
            model_name='event',
            name='medical_specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.medicalspecialty'),
        ),
        migrations.AddField(
            model_name='event',
            name='vaccination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.vaccination'),
        ),
    ]
