# Generated by Django 5.2.4 on 2025-08-17 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_blooddonation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['city', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='blooddonation',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.donationcenter'),
        ),
        migrations.AddConstraint(
            model_name='blooddonation',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'time'), name='uniq_blood_donation_user_date_time'),
        ),
    ]
