# Generated by Django 5.2.4 on 2025-07-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_event_analysis_test_event_medical_specialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blood_donation',
            field=models.BooleanField(default=False),
        ),
    ]
