# Generated by Django 5.2.4 on 2025-07-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_event_blood_donation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='finish_date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('visit', 'Visit to the doctor'), ('vaccination', 'Vaccination'), ('analysis', 'Analysis'), ('donation', 'Blood donation'), ('other', 'Other')], default='other', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='09:00'),
            preserve_default=False,
        ),
    ]
