# Generated by Django 5.2.4 on 2025-07-27 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_event_options_rename_date_event_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('vaccination', 'Vaccination'), ('analysis', 'Analysis'), ('blood donation', 'Blood Donation'), ('other', 'Other'), ('visit', 'Visit')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='vaccination',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.vaccination'),
        ),
    ]
