# Generated by Django 5.2.4 on 2025-07-28 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_event_event_type_alter_event_vaccination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='finish_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='vaccination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.vaccination'),
        ),
    ]
