# Generated by Django 5.2.4 on 2025-08-17 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_switch_blood_donation_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='blood_donation',
            field=models.OneToOneField(blank=True, db_column='blood_donation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='services.blooddonation'),
        ),
        migrations.RenameField(
            model_name='event',
            old_name='blood_donation',
            new_name='blood_donation_fk',
        ),
    ]
