# Generated by Django 5.2.4 on 2025-08-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_event_blood_donation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='blood_donation_fk',
            new_name='blood_donation',
        ),
    ]
