# Generated by Django 5.2.4 on 2025-08-19 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_rename_blood_donation_fk_event_blood_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='analysis_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.analysispackage'),
        ),
    ]
