# Generated by Django 5.2.4 on 2025-07-23 18:56

# Generated by Django 5.2.4 on 2025-07-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
