# Generated by Django 5.2.4 on 2025-08-10 20:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_image_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse', models.PositiveSmallIntegerField(help_text='Heart rate in beats per minute', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(220)])),
                ('blood_pressure', models.PositiveSmallIntegerField(help_text='Blood pressure', validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(250)])),
                ('temperature', models.FloatField(help_text='Body temperature in 36.6°C', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(45)])),
                ('weight', models.FloatField(help_text='Body weight in kilograms 70.5', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(500)])),
                ('height', models.FloatField(help_text='Height in centimeters', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
