# Generated by Django 5.2.4 on 2025-08-20 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_medicaldocument_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('providers_only', 'Healthcare providers only')], default='private', max_length=32)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('appointment_notifications', models.BooleanField(default=True)),
                ('medication_reminders', models.BooleanField(default=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('date_format', models.CharField(choices=[('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='YYYY-MM-DD', max_length=16)),
                ('units', models.CharField(choices=[('metric', 'Metric (kg, °C)'), ('imperial', 'Imperial (lbs, °F)')], default='metric', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
