# Generated by Django 5.2.4 on 2025-08-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(choices=[('America/New_York', 'Eastern Time'), ('America/Chicago', 'Central Time'), ('America/Denver', 'Mountain Time'), ('America/Los_Angeles', 'Pacific Time'), ('Europe/Kyiv', 'Eastern European Time'), ('Europe/Dublin', 'Ireland (Dublin)')], default='Europe/Kyiv', max_length=64),
        ),
    ]
